# Generated by Django 2.2.4 on 2020-04-29 09:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=500)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('auth_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('role', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TFC.Organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'Team_Member',
                'verbose_name_plural': 'Team_Members',
            },
        ),
    ]
