# Generated by Django 2.2.4 on 2020-05-04 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0003_auto_20200501_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='auth_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], max_length=50),
        ),
    ]
