# Generated by Django 2.2.4 on 2020-05-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0004_auto_20200504_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
