# Generated by Django 2.2.4 on 2020-05-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0002_auto_20200429_1301'),
        ('TFC', '0005_auto_20200511_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ScreeningApp.Candidate')),
                ('mobile', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=200)),
                ('availability', models.CharField(choices=[('0 - 10hours per week', '0 - 10hours'), ('10 - 20hours per week', '10 - 20hours'), ('20 - 30hours per week', '20 - 30hours'), ('30 - 40hours per week', '30 - 40hours')], max_length=100)),
                ('current_occupation', models.CharField(choices=[('Student', 'Student'), ('Working Professional', 'Working Professional'), ('Govenment Official', 'Govenment Official')], max_length=200)),
                ('years_of_experience', models.CharField(choices=[('No Experience', 'No Experience'), ('1+ years', '1+ years'), ('2+ years', '2+ years'), ('3+ years', '3+ years'), ('5+ years', '5+ years'), ('10+ years', '10+ years'), ('15+ years', '15+ years'), ('20+ years', '20+ years')], max_length=200)),
                ('profession', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
            },
            bases=('ScreeningApp.candidate',),
        ),
    ]
