# Generated by Django 2.2.4 on 2020-05-15 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0006_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TFC.Organization', verbose_name='Organization'),
            preserve_default=False,
        ),
    ]
