# Generated by Django 2.2.4 on 2020-05-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0006_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(choices=[('0 - 10hours per week', '0 - 10hours per week'), ('10 - 20hours per week', '10 - 20hours per week'), ('20 - 30hours per week', '20 - 30hours per week'), ('30 - 40hours per week', '30 - 40hours per week')], max_length=100),
        ),
    ]
