# Generated by Django 2.2.4 on 2020-05-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0007_volunteer_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='profession',
        ),
    ]
