# Generated by Django 2.2.4 on 2020-05-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0007_auto_20200513_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='education',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='zip_code',
        ),
    ]
