# Generated by Django 2.2.4 on 2020-05-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0008_auto_20200514_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(choices=[('0 - 10 hours per week', '0 - 10 hours per week'), ('10 - 20 hours per week', '10 - 20 hours per week'), ('20 - 30 hours per week', '20 - 30 hours per week'), ('30 - 40 hours per week', '30 - 40 hours per week')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='current_occupation',
            field=models.CharField(choices=[('Student', 'Student'), ('Working Professional', 'Working Professional'), ('Government Official', 'Govenment Official')], max_length=200),
        ),
    ]
