# Generated by Django 2.2.4 on 2020-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0008_remove_volunteer_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
