# Generated by Django 2.2.4 on 2020-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0009_auto_20200514_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='current_occupation',
            field=models.CharField(choices=[('Student', 'Student'), ('Working Professional', 'Working Professional'), ('Government Official', 'Government Official')], max_length=200),
        ),
    ]
