# Generated by Django 2.2.4 on 2020-06-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0009_auto_20200612_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='focus_area',
            field=models.TextField(default='Non Profit'),
            preserve_default=False,
        ),
    ]
