# Generated by Django 2.2.4 on 2021-03-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0010_organization_focus_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
