# Generated by Django 2.2.4 on 2020-04-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('screening_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_question', models.IntegerField()),
                ('total_mark', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name': 'Sub_Category', 'verbose_name_plural': 'Sub_Categories'},
        ),
        migrations.CreateModel(
            name='Candidates_Screening',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.Candidate')),
                ('screening_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.Screening')),
            ],
        ),
    ]
