# Generated by Django 2.2.4 on 2020-04-16 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenings_questions',
            old_name='screening_uuid',
            new_name='screening_id',
        ),
    ]
