# Generated by Django 2.2.4 on 2020-04-27 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('expertise_id', models.AutoField(primary_key=True, serialize=False)),
                ('expertise', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Expertise',
                'verbose_name_plural': 'Expertises',
            },
        ),
        migrations.CreateModel(
            name='Expertise_Area',
            fields=[
                ('expertise_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_of_expertise', models.CharField(max_length=300, unique=True)),
                ('category_of_expertise', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Expertise_Area',
                'verbose_name_plural': 'Expertise_Areas',
            },
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sub_category_name',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Sub_category',
        ),
        migrations.AddField(
            model_name='expertise',
            name='expertise_area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.Expertise_Area'),
        ),
        migrations.AddField(
            model_name='question',
            name='category_of_expertise',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.Expertise_Area'),
        ),
        migrations.AddField(
            model_name='question',
            name='expertise',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.Expertise'),
        ),
    ]
