# Generated by Django 2.2.4 on 2020-04-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0002_auto_20200427_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertise',
            old_name='expertise_area_id',
            new_name='expertise_area',
        ),
    ]
