# Generated by Django 2.2.4 on 2020-04-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0003_screening_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening_Question',
            fields=[
                ('screening_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_ans', models.CharField(max_length=50)),
                ('correct_ans', models.CharField(max_length=50)),
                ('answer_correctness', models.CharField(max_length=10)),
                ('question_id', models.ManyToManyField(to='ScreeningApp.Question')),
            ],
        ),
        migrations.AddField(
            model_name='candidates_screening',
            name='screening_uuid',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidates_screening',
            name='screening_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.Screening_Question'),
        ),
        migrations.DeleteModel(
            name='Screening',
        ),
    ]
