# Generated by Django 2.2.4 on 2020-05-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0003_auto_20200513_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='category_of_expertise',
            new_name='area_of_expertise',
        ),
    ]
