# Generated by Django 2.2.4 on 2020-04-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0003_auto_20200427_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertise',
            old_name='expertise_area',
            new_name='category_of_expertise',
        ),
    ]
