# Generated by Django 2.2.4 on 2020-04-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0005_auto_20200411_1346'),
        ('ScreeningApp', '0005_auto_20200411_1414'),
    ]

    operations = [
    ]
