# Generated by Django 2.2.4 on 2020-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0007_candidate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profession',
            field=models.CharField(default='Engineering', max_length=200),
            preserve_default=False,
        ),
    ]
