# Generated by Django 2.2.4 on 2020-05-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0008_candidate_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.Expertise_Area'),
        ),
    ]
