# Generated by Django 2.2.4 on 2020-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0010_auto_20200518_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='area_of_expertise',
        ),
        migrations.AddField(
            model_name='candidate',
            name='area_of_expertise',
            field=models.ManyToManyField(to='ScreeningApp.Expertise'),
        ),
    ]
