# Generated by Django 2.2.4 on 2020-06-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0011_auto_20200525_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenings',
            name='screening_result',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='screenings',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Closed', 'Closed'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='New', max_length=50),
        ),
    ]
