# Generated by Django 2.2.4 on 2021-01-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0013_auto_20210113_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('option_1', 'option_1'), ('option_2', 'option_2'), ('option_3', 'option_3'), ('option_4', 'option_4')], max_length=100),
        ),
    ]
