# Generated by Django 2.2.4 on 2021-03-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0014_auto_20210122_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, choices=[('option_1', 'option_1'), ('option_2', 'option_2'), ('option_3', 'option_3'), ('option_4', 'option_4')], max_length=100, null=True),
        ),
    ]
