# Generated by Django 2.2.4 on 2021-03-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0015_auto_20210315_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
