# Generated by Django 2.2.4 on 2021-03-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0016_auto_20210315_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
