# Generated by Django 2.2.4 on 2021-03-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0018_expertise_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenings',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Open', max_length=50),
        ),
    ]
