# Generated by Django 2.2.4 on 2021-03-20 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0019_auto_20210320_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenings',
            name='created_on',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='screenings',
            name='first_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenings',
            name='second_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenings',
            name='third_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
