# Generated by Django 3.2 on 2021-12-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0020_auto_20210320_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='area_of_expertise',
            field=models.ManyToManyField(blank=True, null=True, to='ScreeningApp.Expertise'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('Intermediate', 'Intermediate'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='level_of_expertise',
            field=models.CharField(blank=True, choices=[('Entry Level', 'Entry Level'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ScreeningApp.expertise_area'),
        ),
    ]
