# Generated by Django 2.2.4 on 2020-05-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TFC', '0003_auto_20200501_1252'),
        ('HFCCore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TFC.organization',),
        ),
    ]
