# Generated by Django 3.0.6 on 2020-05-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0003_organization_problem_statement_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
