# Generated by Django 2.2.4 on 2020-06-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningApp', '0011_auto_20200525_1508'),
        ('HFCCore', '0005_community_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community_Member',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ScreeningApp.Candidate')),
                ('type', models.CharField(choices=[('Contributor', 'Contributor'), ('Mentor', 'Mentor')], default='Contributor', max_length=50)),
                ('coder_profile', models.CharField(max_length=100)),
                ('linkedin_profile', models.CharField(max_length=100)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HFCCore.Community_Organization')),
            ],
            options={
                'verbose_name': 'Community_Member',
                'verbose_name_plural': 'Community_Members',
            },
            bases=('ScreeningApp.candidate',),
        ),
    ]
