# Generated by Django 2.2.4 on 2020-06-29 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0009_problem_statement_issue_area_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_member',
            name='years_of_experience',
            field=models.CharField(choices=[('No Experience', 'No Experience'), ('1+ years', '1+ years'), ('2+ years', '2+ years'), ('3+ years', '3+ years'), ('5+ years', '5+ years'), ('10+ years', '10+ years'), ('15+ years', '15+ years'), ('20+ years', '20+ years')], default='No Experience', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community_member',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HFCCore.Community_Organization'),
        ),
    ]
