# Generated by Django 2.2.4 on 2020-06-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0010_auto_20200629_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_member',
            name='coder_profile',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='community_member',
            name='linkedin_profile',
            field=models.URLField(),
        ),
    ]
