# Generated by Django 2.2.4 on 2020-11-19 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0012_auto_20201119_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statement',
            name='partner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HFCCore.Partner'),
        ),
    ]
