# Generated by Django 2.2.4 on 2020-11-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0013_auto_20201119_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statement',
            name='proposed_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem_statement',
            name='related_link',
            field=models.URLField(blank=True),
        ),
    ]
