# Generated by Django 2.2.4 on 2020-11-26 09:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0014_auto_20201119_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_organization',
            name='organization_name_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='organization_name'),
        ),
    ]
