# Generated by Django 2.2.4 on 2020-12-21 09:42

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0017_auto_20201221_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_area', models.CharField(max_length=100)),
                ('issue_area_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='issue_area')),
            ],
        ),
        migrations.AddField(
            model_name='problem_statement',
            name='issue_area',
            field=models.ManyToManyField(to='HFCCore.Issue_Area'),
        ),
    ]
