# Generated by Django 2.2.4 on 2021-01-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0018_auto_20201221_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statement',
            name='related_link',
            field=models.TextField(blank=True),
        ),
    ]
