# Generated by Django 2.2.4 on 2021-01-21 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0019_auto_20210113_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_member',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community_member',
            name='commit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community_member',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HFCCore.Project'),
        ),
        migrations.AlterField(
            model_name='community_member',
            name='coder_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community_member',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='funded_by',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
