# Generated by Django 2.2.4 on 2021-01-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0020_auto_20210121_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community_member',
            name='project',
        ),
        migrations.AddField(
            model_name='community_member',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='HFCCore.Project'),
        ),
    ]
