# Generated by Django 2.2.4 on 2021-02-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0021_auto_20210125_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_organization',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='HFCCore.Project'),
        ),
    ]
