# Generated by Django 2.2.4 on 2021-02-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0022_community_organization_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_organization',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
