# Generated by Django 3.2 on 2021-07-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0023_community_organization_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_area',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue_area',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue_area',
            name='related_link',
            field=models.TextField(blank=True),
        ),
    ]
