# Generated by Django 3.2 on 2021-07-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0024_auto_20210715_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue_area',
            old_name='definition',
            new_name='context',
        ),
        migrations.RenameField(
            model_name='issue_area',
            old_name='description',
            new_name='issue_overview',
        ),
        migrations.RenameField(
            model_name='issue_area',
            old_name='related_link',
            new_name='related_information',
        ),
        migrations.AddField(
            model_name='issue_area',
            name='technology_intervention',
            field=models.TextField(blank=True),
        ),
    ]
