# Generated by Django 3.2 on 2021-07-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0025_auto_20210717_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_area',
            name='issue_brief',
            field=models.TextField(blank=True),
        ),
    ]
