# Generated by Django 3.2 on 2021-07-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0026_issue_area_issue_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_area',
            name='issue_brief',
            field=models.TextField(blank=True, help_text='This text is used for SEO purpose'),
        ),
    ]
