# Generated by Django 3.2 on 2021-07-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0028_auto_20210719_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='funded_by',
        ),
    ]
