# Generated by Django 3.2 on 2021-07-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0030_project_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_desc',
            new_name='project_overview',
        ),
    ]
