# Generated by Django 3.2 on 2021-07-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0031_rename_project_desc_project_project_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_area',
            name='issue_sub_header',
            field=models.TextField(blank=True, help_text='This text is used for SEO purpose'),
        ),
        migrations.AlterField(
            model_name='issue_area',
            name='issue_brief',
            field=models.TextField(blank=True),
        ),
    ]
