# Generated by Django 3.2 on 2021-07-23 07:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0033_auto_20210723_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statement',
            name='title_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='brief'),
        ),
    ]
