# Generated by Django 3.2 on 2021-07-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0034_alter_problem_statement_title_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_organization',
            name='is_public',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10, null=True),
        ),
    ]
