# Generated by Django 3.2.4 on 2021-09-24 05:29

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0036_rename_brief_problem_statement_problem_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_statement',
            name='about_yourself',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem_statement',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem_statement',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem_statement',
            name='phone_number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem_statement',
            name='title_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='problem_statement'),
        ),
    ]
