# Generated by Django 3.2.4 on 2021-09-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0037_auto_20210924_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statement',
            name='about_yourself',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem_statement',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem_statement',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem_statement',
            name='phone_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem_statement',
            name='related_link',
            field=models.TextField(),
        ),
    ]
