# Generated by Django 3.2.4 on 2021-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0038_auto_20210924_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_statement',
            name='organisation',
            field=models.TextField(blank=True),
        ),
    ]
