# Generated by Django 3.2.4 on 2021-10-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0039_problem_statement_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ideation', 'Ideation'), ('Work In Progress', 'Work In Progress'), ('Live', 'Live')], default='Draft', max_length=100),
        ),
    ]
