# Generated by Django 3.2 on 2021-11-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0040_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statement',
            name='about_yourself',
            field=models.TextField(blank=True, verbose_name='Comments From Suggestor'),
        ),
        migrations.AlterField(
            model_name='problem_statement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Suggester Email'),
        ),
        migrations.AlterField(
            model_name='problem_statement',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Suggester Name'),
        ),
        migrations.AlterField(
            model_name='problem_statement',
            name='organisation',
            field=models.TextField(blank=True, verbose_name='Suggester Organisation'),
        ),
        migrations.AlterField(
            model_name='problem_statement',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Suggester Phone Number'),
        ),
        migrations.AlterField(
            model_name='problem_statement',
            name='problem_statement',
            field=models.TextField(),
        ),
    ]
