# Generated by Django 3.2 on 2021-11-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0041_auto_20211126_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statement',
            name='organisation',
            field=models.CharField(blank=True, max_length=500, verbose_name='Suggester Organisation'),
        ),
    ]
