# Generated by Django 3.2 on 2021-12-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0043_community_member_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community_member',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('No Experience', 'No Experience'), ('1+ years', '1+ years'), ('2+ years', '2+ years'), ('3+ years', '3+ years'), ('5+ years', '5+ years'), ('10+ years', '10+ years'), ('15+ years', '15+ years'), ('20+ years', '20+ years')], max_length=200, null=True),
        ),
    ]
