# Generated by Django 3.2 on 2022-01-12 05:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0045_alter_project_partner_project_involvement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_statement',
            name='title_slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='problem_statement', unique=True),
        ),
    ]
