# Generated by Django 2.2.6 on 2020-01-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20200123_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
