# Generated by Django 3.2 on 2021-07-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
