# Generated by Django 3.2.4 on 2021-10-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsEngine', '0002_rename_agenda_events_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='email_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
