# Generated by Django 3.2.4 on 2021-10-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsEngine', '0003_auto_20211003_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='registration_status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
