# Generated by Django 3.2.4 on 2021-10-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsEngine', '0005_auto_20211003_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='email_content',
            new_name='email_confirmation',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='registration_status',
            new_name='registration',
        ),
    ]
