# Generated by Django 3.2.4 on 2021-10-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsEngine', '0006_auto_20211004_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='events',
            name='banner_color',
            field=models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], default='Light', max_length=10),
        ),
        migrations.AddField(
            model_name='events',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
