# Generated by Django 3.2.4 on 2021-11-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsEngine', '0007_auto_20211009_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='logo',
        ),
        migrations.AddField(
            model_name='events',
            name='icon',
            field=models.ImageField(blank=True, help_text='Resolution 84 * 84', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='banner',
            field=models.ImageField(blank=True, help_text='Resolution 1500 * 300', null=True, upload_to=''),
        ),
    ]
