# Generated by Django 3.2.4 on 2021-11-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsEngine', '0008_auto_20211117_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='truncated_descripton',
            field=models.BooleanField(default=False),
        ),
    ]
