# Generated by Django 3.2.4 on 2021-11-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsEngine', '0009_events_truncated_descripton'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='keywords',
            field=models.TextField(default='Event'),
        ),
    ]
