# Generated by Django 3.2.4 on 2021-11-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsEngine', '0010_events_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='truncated_descripton',
            new_name='truncated_description',
        ),
    ]
