# Generated by Django 3.2 on 2021-12-17 06:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsEngine', '0012_events_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title_slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique=True),
        ),
    ]
