# Generated by Django 3.2 on 2021-12-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsEngine', '0013_alter_events_title_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='open_graph_banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
