# Generated by Django 3.2 on 2022-01-07 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HFCCore', '0045_alter_project_partner_project_involvement'),
        ('EventsEngine', '0014_events_open_graph_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_details', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsEngine.events', verbose_name='Event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HFCCore.community_member', verbose_name='Event Speaker')),
            ],
            options={
                'verbose_name': 'Event Speaker',
                'verbose_name_plural': 'Event Speakers',
            },
        ),
    ]
